---
- set_fact:
    filter: "{{ 'tag' + ':' + 'student_id=' + student_id }}"

- name: Configure Tower Inventory Group
  tower_group:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    name: "{{ tower_inventory_group }}"
    description: "{{ tower_inventory_group_description }}"
    inventory: "{{ tower_inventory }}"
    state: present

- name: Add OSEv3 Group
  tower_group:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    name: "{{ tower_openshift_install_group }}"
    description: "{{ tower_openshift_install_group_description }}"
    source: "manual"
    inventory: "{{ tower_inventory }}"
    state: present
    variables: "{{ lookup('template', 'OSEv3.yml.j2') }}"
  when: tower_openshift_install_group_config|bool == true

- name: Add OSEv3 Children
  tower_group:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    name: "{{ item }}"
    description: "{{ item + '_description' }}"
    source: "manual"
    inventory: "{{ tower_inventory }}"
    state: present
  with_items:
    - "{{ tower_openshift_masters_group }}"
    - "{{ tower_openshift_etcd_group }}"
    - "{{ tower_openshift_nodes_group }}"
    - "{{ tower_master_tag }}"
    - "{{ tower_node_tag }}"
  when: 
    - tower_openshift_masters_group_config|bool == true
    - tower_openshift_etcd_group_config|bool == true
    - tower_openshift_nodes_group_config|bool == true

- name: Associate OSEv3 Groups
  command: >
    tower-cli group associate
      --group "{{ item.0 }}"
      --parent "{{ item.1 }}"
      --inventory "{{ tower_inventory }}"
      "{{ tower_cli_verbosity }}"
  with_together:
    - [ "{{ tower_openshift_nodes_group }}", "{{ tower_node_tag }}", "{{ tower_openshift_masters_group }}", "{{ tower_master_tag }}", "{{ tower_openshift_etcd_group }}", "{{ tower_master_tag }}" ]
    - [ "{{ tower_openshift_install_group }}", "{{ tower_openshift_nodes_group }}", "{{ tower_openshift_nodes_group }}", "{{ tower_openshift_masters_group }}", "{{ tower_openshift_masters_group }}", "{{ tower_openshift_etcd_group }}" ]
  when: 
    - tower_openshift_masters_group_config|bool == true
    - tower_openshift_etcd_group_config|bool == true
    - tower_openshift_nodes_group_config|bool == true
