---
deployment_type: openshift-enterprise
openshift_additional_repos:
- id: ocp
  name: OCP
  baseurl: http://repo.osp.example.com/pub/rhel-7-server-ose-3.4-rpms/
  enabled: 1
  gpgcheck: 0
- id: rhel7
  name: rhel7
  baseurl: http://repo.osp.example.com/pub/rhel-7-server-rpms/
  enabled: 1
  gpgcheck: 0
- id: rhel7-extras
  name: rhel7-extras
  baseurl: http://repo.osp.example.com/pub/rhel-7-server-extras-rpms/
  enabled: 1
  gpgcheck: 0
openshift_docker_additional_registries: repo.osp.example.com:5000
openshift_docker_insecure_registries: repo.osp.example.com:5000
osm_use_cockpit: no
openshift_master_default_subdomain: apps.example.com
openshift_master_identity_providers:
- name: htpasswd_auth
  login: True
  challenge: True
  kind: HTPasswdPasswordIdentityProvider
  filename: /etc/origin/master/htpasswd
openshift_master_htpasswd_users:
  user1: $apr1$7ctI4q/Q$84OX0FrpqM3hzlO9CUCh0.
openstack_config_file_contents: "{{ lookup('file', lookup('env', 'OS_CLIENT_CONFIG_FILE')) | from_yaml }}"
openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ openstack_config_file_contents.clouds.devstack.auth.auth_url }}"
openshift_cloudprovider_openstack_username: "{{ openstack_config_file_contents.clouds.devstack.auth.username }}"
openshift_cloudprovider_openstack_password: "{{ openstack_config_file_contents.clouds.devstack.auth.password }}"
openshift_cloudprovider_openstack_tenant_name: "{{ openstack_config_file_contents.clouds.devstack.auth.project_name }}"
openshift_hosted_registry_storage_kind: object
openshift_hosted_registry_storage_provider: swift
openshift_hosted_registry_storage_swift_authurl: "{{ openstack_config_file_contents.clouds.devstack.auth.auth_url }}"
openshift_hosted_registry_storage_swift_username: "{{ openstack_config_file_contents.clouds.devstack.auth.username }}"
openshift_hosted_registry_storage_swift_password: "{{ openstack_config_file_contents.clouds.devstack.auth.password }}"
openshift_hosted_registry_storage_swift_container: openshift_registry
openshift_hosted_registry_storage_swift_tenant: "{{ openstack_config_file_contents.clouds.devstack.auth.project_name }}"
openshift_hosted_metrics_deploy: yes
openshift_hosted_metrics_storage_kind: dynamic
os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
osn_storage_plugin_deps: []
openshift_node_labels:
  region: "{{ openstack.metadata.node_type }}"
  zone: default
