---
- name: Configure Job Template for Deploy-Install
  tower_job_template:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    job_type: run
    name: "{{ tower_job_template_deploy_install }}"
    description: "{{ tower_job_template_deploy_install_description }}"
    state: present
    inventory: "{{ tower_inventory }}"
    project: "{{ tower_project_install }}"
    playbook: "{{ tower_job_template_deploy_install_playbook }}"
    become_enabled: "{{ tower_job_template_deploy_install_become_enabled }}"
    machine_credential: "{{ tower_credential_machine }}"
    cloud_credential: "{{ tower_credential_cloud }}"

- name: Associate the AWS credential to the template
  command: >
    tower-cli job_template associate_credential
      --job-template "{{ tower_job_template_deploy_install }}"
      --credential "{{ tower_credential_cloud }}"
      --tower-username "{{ tower_username }}"
      --tower-password "{{ tower_password }}"
...
