---
- name: Configure Job Template for Scaleup-Configure
  tower_job_template:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    job_type: run
    name: "{{ tower_job_template_scaleup_configure }}"
    description: "{{ tower_job_template_scaleup_configure_description }}"
    state: present
    inventory: "{{ tower_inventory }}"
    cloud_credential: "{{ tower_credential_cloud }}"
    project: "{{ tower_project_provision_and_configure }}"
    playbook: "{{ tower_job_template_scaleup_configure_playbook }}"
    machine_credential: "{{ tower_credential_machine }}"
...
