---
tower_admin_password: false
tower_user_add: false
tower_cli_credentials_config: false
tower_prereqs_config: false
tower_org_config: false
tower_credential_machine_config: false
tower_credential_cloud_config: false
tower_inventory_config: false
tower_inventory_group_config: false
tower_openshift_install_group_config: false
tower_openshift_masters_group_config: false
tower_openshift_etcd_group_config: false
tower_openshift_nodes_group_config: false
tower_openshift_new_nodes_group_config: false
tower_project_provision_and_configure_config: false
tower_project_install_config: false
tower_job_template_self_configure_config: false
tower_job_template_deploy_provision_config: false
tower_job_template_deploy_install_config: false
tower_job_template_deploy_configure_config: false
tower_job_template_scaleup_provision_config: false
tower_job_template_scaleup_install_config: false
tower_job_template_scaleup_configure_config: false
tower_job_template_terminate_ocp_config: false
tower_job_template_terminate_all_config: false
tower_workflow_template_deploy_config: false
tower_workflow_template_scaleup_config: false
tower_workflow_template_terminate_config: false
tower_ssl_config: false
...
