---
# This is used to fully configure Tower as well as automatically launch the deploy and scale jobs. To terminate override the 'tower_workflow_job_terminate_launch' variable
# NOTE: For the current run of labs the prereqs are already in the AMI so are set to false here.
tower_admin_password: true
tower_user_add: true
tower_cli_credentials_config: true
tower_prereqs_config: false
tower_org_config: true
tower_credential_machine_config: false
tower_credential_cloud_config: false
tower_inventory_config: true
tower_inventory_group_config: true
tower_openshift_install_group_config: true
tower_openshift_masters_group_config: true
tower_openshift_etcd_group_config: true
tower_openshift_nodes_group_config: true
tower_openshift_new_nodes_group_config: true
tower_project_provision_and_configure_config: true
tower_project_install_config: true
tower_job_template_self_configure_config: true
tower_job_template_deploy_provision_config: true
tower_job_template_deploy_prerequisites_config: true
tower_job_template_deploy_install_config: true
tower_job_template_deploy_configure_config: true
tower_job_template_scaleup_provision_config: true
tower_job_template_scaleup_install_config: true
tower_job_template_scaleup_configure_config: true
tower_job_template_terminate_ocp_config: true
tower_job_template_terminate_all_config: true
tower_workflow_template_deploy_config: true
tower_workflow_template_scaleup_config: true
tower_workflow_template_terminate_config: true
tower_job_self_configure_launch: false
tower_workflow_job_deploy_launch: true
tower_workflow_job_scaleup_launch: true
tower_workflow_job_terminate_launch: false
...
