---
- name: Set Tower CLI Host
  command: tower-cli config host {{ tower_host }}

- name: Set Tower CLI Username
  command: tower-cli config username {{ tower_username }}

- name: Set Tower CLI Password
  command: tower-cli config password {{ tower_password }}
  no_log: True

...
