---
- name: Launch Job for Self-Configure - this will block while the job runs and will wait up to {{ tower_job_self_configure_launch_async|int // 60 }} minutes to complete, see Tower UI Jobs for detailed progress
  command: tower-cli job launch --job-template {{ tower_job_template_self_configure }} --monitor
  async: "{{ tower_job_self_configure_launch_async }}"
  poll: "{{ tower_job_self_configure_launch_poll }}"

