---
- name: Configure Job Template for Terminate-All
  tower_job_template:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    job_type: run
    name: "{{ tower_job_template_terminate_all }}"
    description: "{{ tower_job_template_terminate_all_description }}"
    state: present
    inventory: "{{ tower_inventory }}"
    cloud_credential: "{{ tower_cloud_credential }}"
    project: "{{ tower_project_provision_and_configure }}"
    playbook: "{{ tower_job_template_terminate_all_playbook }}"
    machine_credential: "{{ tower_machine_credential }}"

- name: Update Job Template for Terminate-All with Extra Vars
  command: >
    tower-cli job_template modify
      --name="{{ tower_job_template_terminate_all }}"
      --extra-vars="{{ tower_job_template_terminate_all_extra_vars }}"
      "{{ tower_cli_verbosity }}"

