---
- name: Enable OpenShift repository
  command: >
    subscription-manager repos
      --enable="rhel-7-server-ose-{{ openshift_deploy_version }}-rpms"
  ignore_errors: yes
  become: true

- name: Install package requirements for Tower CLI
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ tower_yum_packages }}"

- name: Pip install requirements for Tower CLI
  pip:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ tower_pip_packages }}"

- debug:
    var: "{{ item }}"
    verbosity: 2
  with_items:
    - hostvars[inventory_hostname].friendly_name
    - student_id
    - filter
    - tower_host
...
