- name: Copy Workflow Template Extra Vars for Deploy
  template:
    src: "{{ tower_workflow_template_deploy_extra_vars }}"
    dest: "/tmp/{{ tower_workflow_template_deploy_extra_vars }}"
  when: tower_workflow_template_deploy_config|bool == true

- name: Create Workflow Template for Deploy
  command: >
    tower-cli workflow create
      --name="{{ tower_workflow_template_deploy }}"
      --description="{{ tower_workflow_template_deploy_description }}"
      --organization="{{ tower_org }}"
      --extra-vars="@/tmp/{{ tower_workflow_template_deploy_extra_vars }}"
      "{{ tower_cli_verbosity }}"
  when: tower_workflow_template_deploy_config|bool == true

- debug:
    var: "{{ item }}"
    verbosity: 2
  with_items:
    - tower_workflow_template_deploy
    - tower_workflow_template_deploy_schema

- name: Copy Workflow Template Schema for Deploy
  template:
    src: "{{ tower_workflow_template_deploy_schema_path }}"
    dest: "/tmp/{{ tower_workflow_template_deploy_schema_path }}"
  when: tower_workflow_template_deploy_config|bool == true

- name: Create Workflow Schema for Deploy
  command: tower-cli workflow schema {{ tower_workflow_template_deploy }} @/tmp/{{ tower_workflow_template_deploy_schema_path }} "{{ tower_cli_verbosity }}"
  when: tower_workflow_template_deploy_config|bool == true
